In [35]:
import pandas as pd
import numpy as np

In [36]:
df= pd.read_csv("./covid_toy.csv")
df.sample(5)

    age  gender  fever   cough       city has_covid
3    31  Female   98.0    Mild    Kolkata        No
30   15    Male  101.0    Mild      Delhi       Yes
32   34  Female  101.0  Strong      Delhi       Yes
64   42    Male  104.0    Mild     Mumbai        No
63   10    Male  100.0    Mild  Bangalore        No

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [38]:
from sklearn.model_selection import train_test_split


X_train,X_test,Y_train,Y_test=   train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [39]:
X_train

    age  gender  fever   cough       city
18   64  Female   98.0    Mild  Bangalore
6    14    Male  101.0  Strong  Bangalore
47   18  Female  104.0    Mild  Bangalore
36   38  Female  101.0    Mild  Bangalore
67   65    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
84   69  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata
91   38    Male    NaN    Mild      Delhi
75    5    Male  102.0    Mild    Kolkata
41   82    Male    NaN    Mild    Kolkata

[80 rows x 5 columns]

In [40]:
Y_test

42    Yes
17     No
45     No
50    Yes
19    Yes
58    Yes
97     No
3      No
28     No
83     No
69     No
38    Yes
74     No
10     No
56     No
52    Yes
94    Yes
76    Yes
60    Yes
71     No
Name: has_covid, dtype: object

AAM  ZINDGI

In [41]:
from sklearn.impute   import SimpleImputer


se=SimpleImputer()

X_train_fever=  se.fit_transform(X_train[['fever']])

X_test_fever=  se.fit_transform(X_test[['fever']])


X_test_fever.shape

(20, 1)

In [42]:
#ordinal encoding for gender and cough 
from  sklearn.preprocessing   import OrdinalEncoder


OE=  OrdinalEncoder(categories=[['Mild','Strong']])


X_train_Cough=   OE.fit_transform(X_train[['cough']])

X_test_Cough=   OE.fit_transform(X_test[['cough']])


X_train_Cough.shape

(80, 1)

In [55]:
## one Hot Encoding on the gender and city

from sklearn.preprocessing  import OneHotEncoder



OHE=  OneHotEncoder(drop='first')


X_train_OHE=  OHE.fit_transform(X_train[['gender','city']]).value


X_test_OHE   = OHE.fit_transform(X_test[['gender','city']])


X_train_OHE.shape

AttributeError: 'csr_matrix' object has no attribute 'value'

In [44]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [51]:
X_train_OHE
# X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_Cough,X_train_OHE),axis=1)
# # also the test data
# X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_Cough,X_test_OHE),axis=1)

# X_train_transformed.shape

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 89 stored elements and shape (80, 4)>